var annotated_dup =
[
    [ "StorageQuery", "namespace_storage_query.html", "namespace_storage_query" ],
    [ "_OSSlotMaxCurrSpeed", "struct___o_s_slot_max_curr_speed.html", "struct___o_s_slot_max_curr_speed" ],
    [ "_OSSlotSpeed", "struct___o_s_slot_speed.html", "struct___o_s_slot_speed" ],
    [ "_SCSI_PASS_THROUGH", "struct___s_c_s_i___p_a_s_s___t_h_r_o_u_g_h.html", "struct___s_c_s_i___p_a_s_s___t_h_r_o_u_g_h" ],
    [ "_SCSI_PASS_THROUGH_WITH_BUFFERS", "struct___s_c_s_i___p_a_s_s___t_h_r_o_u_g_h___w_i_t_h___b_u_f_f_e_r_s.html", "struct___s_c_s_i___p_a_s_s___t_h_r_o_u_g_h___w_i_t_h___b_u_f_f_e_r_s" ],
    [ "_SCSI_PASS_THROUGH_WITH_BUFFERS24", "struct___s_c_s_i___p_a_s_s___t_h_r_o_u_g_h___w_i_t_h___b_u_f_f_e_r_s24.html", "struct___s_c_s_i___p_a_s_s___t_h_r_o_u_g_h___w_i_t_h___b_u_f_f_e_r_s24" ],
    [ "_SlotMaxCurrSpeed", "struct___slot_max_curr_speed.html", "struct___slot_max_curr_speed" ],
    [ "_SlotSpeed", "struct___slot_speed.html", "struct___slot_speed" ],
    [ "_SMART_ATTRIBUTE", "struct___s_m_a_r_t___a_t_t_r_i_b_u_t_e.html", "struct___s_m_a_r_t___a_t_t_r_i_b_u_t_e" ],
    [ "_VOLUME_DISK_EXTENTS_LX", "struct___v_o_l_u_m_e___d_i_s_k___e_x_t_e_n_t_s___l_x.html", "struct___v_o_l_u_m_e___d_i_s_k___e_x_t_e_n_t_s___l_x" ],
    [ "CAboutDlg", "class_c_about_dlg.html", "class_c_about_dlg" ],
    [ "CAtaSmart", "class_c_ata_smart.html", "class_c_ata_smart" ],
    [ "CButtonCx", "class_c_button_cx.html", "class_c_button_cx" ],
    [ "CButtonEx", "class_c_button_ex.html", "class_c_button_ex" ],
    [ "CComboBoxCx", "class_c_combo_box_cx.html", "class_c_combo_box_cx" ],
    [ "CDHtmlDialogEx", "class_c_d_html_dialog_ex.html", "class_c_d_html_dialog_ex" ],
    [ "CDHtmlMainDialog", "class_c_d_html_main_dialog.html", "class_c_d_html_main_dialog" ],
    [ "CDialogCx", "class_c_dialog_cx.html", "class_c_dialog_cx" ],
    [ "CDiskInfoApp", "class_c_disk_info_app.html", "class_c_disk_info_app" ],
    [ "CDiskInfoDlg", "class_c_disk_info_dlg.html", "class_c_disk_info_dlg" ],
    [ "CDnpService", "class_c_dnp_service.html", "class_c_dnp_service" ],
    [ "CEditEx", "class_c_edit_ex.html", "class_c_edit_ex" ],
    [ "CFontComboBox", "class_c_font_combo_box.html", "class_c_font_combo_box" ],
    [ "CFontSelection", "class_c_font_selection.html", "class_c_font_selection" ],
    [ "CGraphDlg", "class_c_graph_dlg.html", "class_c_graph_dlg" ],
    [ "CHealthDlg", "class_c_health_dlg.html", "class_c_health_dlg" ],
    [ "CListCtrlEx", "class_c_list_ctrl_ex.html", "class_c_list_ctrl_ex" ],
    [ "CMainDialog", "class_c_main_dialog.html", "class_c_main_dialog" ],
    [ "COptionDlg", "class_c_option_dlg.html", "class_c_option_dlg" ],
    [ "CSettingDlg", "class_c_setting_dlg.html", "class_c_setting_dlg" ],
    [ "CSoundSettingDlg", "class_c_sound_setting_dlg.html", "class_c_sound_setting_dlg" ],
    [ "CStaticCx", "class_c_static_cx.html", "class_c_static_cx" ],
    [ "CStaticEx", "class_c_static_ex.html", "class_c_static_ex" ],
    [ "CTemperatureDlg", "class_c_temperature_dlg.html", "class_c_temperature_dlg" ],
    [ "DiskDriveInfo", "struct_disk_drive_info.html", "struct_disk_drive_info" ]
];